name: matrix
on:  
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix: 
        operating-system: [ubuntu-latest,macos-latest, windows-latest]
        node-version: [12, 14, 16]
    runs-on: ${{  matrix.operating-system }}
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: ${{  matrix.node-version}}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
